### PR TITLE
Do not require the `OC` variable to be set

### LINKED ISSUE #361: v2.2.0 depends on `OC` global
https://github.com/nextcloud/nextcloud-logger/blob/69157312bb071d3152c54f4686aacb2df014042e/lib/LoggerBuilder.ts#L18 doesn't work if `OC` is undefined. That happens with rare loading order problems but also in testing environments.

The library can work without the global, so I wouldn't make this a hard dependency. @susnux how about ``OC?.config?.loglevel`` instead of ``OC.config?.loglevel``?

### PR DESCRIPTION
**Pull request by susnux**
Fixes #361

This makes the library more robust against loading order problems
and reduces problems with testing setups.

### CODE REVIEW

**Review by ChristophWurst — APPROVED** [review]
Thanks!

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Please let's make sure to deprecate 2.2.0 on npm afterwards please

**Comment by skjnldsv** [comment]
cc @juliushaertl

**Comment by ChristophWurst** [comment]
> Please let's make sure to deprecate 2.2.0 on npm afterwards please

Deprecate?

**Comment by skjnldsv** [comment]
> Deprecate?



https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions#deprecating-a-single-version-of-a-package

**Comment by ChristophWurst** [comment]
I know what deprecation means. NPM will install the newer version anyway. Dependabot will also update all repos that use 2.2.0.

**Pull request merged**
